name: CICD
on:
  push:
    branches: [master]
jobs:
  test-and-package:
    runs-on: ubuntu-latest
    env:
      PYTEST_REPORT_PATH: report.html
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: "Install project dependencies"
        run: pip install -r requirements.txt
      - name: "Run tests and code coverage analysis"
        run: pytest test.py --html=${{ env.PYTEST_REPORT_PATH }} --self-contained-html
  publish-package-as-artifact:
    needs: [test-and-package]
    runs-on: ubuntu-latest
    env:
      PYTEST_REPORT_PATH: report.html
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Archive pytest reports"
        uses: actions/upload-artifact@v3
        if: ${{!cancelled()}}
        with:
          name: "Test and reports"
          path: |
            ${{ env.PYTEST_REPORT_PATH }} 

